version: "3"
services:
  terraform:
    image: hashicorp/terraform:latest # 実際の開発に使用する際には固定が望ましい
    volumes:
      - ~/.aws:/root/.aws:ro
      - ./tf:/workdir # この場合、 ./tf ディレクトリに置いた ファイルが dockerコンテナ内に置かれ、そのうち .tf を拡張子とするファイルが実行対象となる
    working_dir: "/workdir"
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_REGION
      - AWS_DEFAULT_REGION
      - AWS_PROFILE=${AWS_PROFILE}
