# 備考
# {DB_NAME} と記載すると .envファイルのDB_NAMEを参照できる

# compose ファイルフォーマットのバージョン。
# バージョンにより、compose file （docker-compose.yml）の書き方が異なる
version: '3'

# アプリケーションを動かすための各要素（DB、webサーバなど）の設定を記載
# build:
#   - Dockerfileの置き場所（ComposeFileを実行し、ビルドされるときのpath）
# volumes:
#   - マウントする設定ファイルのpath。
#   - コロン（:）がある場合、左側のホストOSのパスのデータが、右側のコンテナのパスにマウントされる
# ports:
#   - Imageを立ち上げる時のポート番号。
#   - <Host IP>:<Host Port>:<Container Port> の形式で書く
# restart:
#   - 再起動ポリシーの設定。
#   - 「- restart: always」 と記述すると、Dockerデーモンの起動時やホストOSの起動時に、自動的にコンテナが開始される
#   - ただし、開発時には有効にしないほうが良いかもしれない
services:
  www:
    image: php:8.1-rc-fpm
    volumes:
      - ../Docker/Server/vimrc/.vimrc:/root/.vimrc
      - ../www/:/var/www/html
    ports:
      - 80:8000
    working_dir: /var/www/html
    command: php -S 0.0.0.0:8000 -t ./
